#!/bin/bash

# Проверяем, существует ли виртуальное окружение
if [ ! -d "./venv" ]; then
  echo "Виртуальное окружение 'venv' не найдено. Создайте его перед запуском."
  exit 1
fi

# Активируем виртуальное окружение
source ./venv/bin/activate

# Проверяем, установлен ли uvicorn
if ! command -v uvicorn &> /dev/null; then
  echo "Uvicorn не установлен. Установите его с помощью 'pip install uvicorn'."
  deactivate
  exit 1
fi

# Запускаем приложение
uvicorn app.main:app
