"""Add user relationship to Reservation

Revision ID: 4d76343b4dc4
Revises: 152fb899199b
Create Date: 2022-12-16 22:57:37.055445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d76343b4dc4"
down_revision = "152fb899199b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reservation", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_reservation_user_id_user", "user", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reservation", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_reservation_user_id_user", type_="foreignkey"
        )
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
