"""Add description to MeetingRoom

Revision ID: b6b77583bcc1
Revises: e1e721f7ac0f
Create Date: 2022-11-23 18:26:09.935130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b6b77583bcc1"
down_revision = "e1e721f7ac0f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meetingroom", sa.Column("description", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meetingroom", "description")
    # ### end Alembic commands ###
